# site settings
title: versae
subtitle: es
email: versae@gmail.com
description: Digital Humanist, Machine Learning Practioner, Researcher<br />Currently working at the Center for Interdisciplinary Digital Research, <br />Stanford University Libraries.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 557 Escondido Mall
city: Stanford
state: CA
zip_code: 94305
country: United States of America
phone: (650) 206-3888

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com/versae
github_url: https://github.com/versae/
gitlab_url: 
googleplus_url: https://plus.google.com/u/0/+versae
instagram_url: 
linkedin_url: https://www.linkedin.com/in/versae
pinterest_url:
slack_url:
twitter_url: https://twitter.com/versae

# build settings
markdown: kramdown

sass:
  style: compressed
